#Create a new deployment called nginx-deploy, with one signle container called nginx, image nginx:1.16 and 4 replicas. 
#The deployment should use RollingUpdate strategy with maxSurge=1, and maxUnavailable=2.
#Next upgrade the deployment to version 1.17 using rolling update.
#Finally, once all pods are updated, undo the update and go back to the previous version.

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy
  name: nginx-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-deploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy
    spec:
      containers:
      - image: nginx:1.16
        name: nginx
        resources: {}
status: {}
